### ISSUE TITLE
Framework Shutdown

### ISSUE THREAD

**Issue by skymania** [isparkes/OpenRate#1]
Calling Framework:Shutdown=true in the ECI stops all the pipelines, but the framework isn't closed and the process keeps running with inactive pipelines.

**Comment by isparkes** [comment]
Hi, does this happen when there is an Exception which causes one of the pipes to remain in an unfinished transaction state, or some other reason? Can you describe the steps to re-create, or provide a simple test harness to show the problem?

**Comment by skymania** [comment]
Hi Ian.
No it dosen't happen because there would be an Exception, because I haven't send anything threw the pipeline to process. I only started up the application and then called Framework shutdown over the ECI.

**Comment by isparkes** [comment]
OK, I will investigate. Which application are you seeing this with? Is it one of the test applications?

**Comment by skymania** [comment]
Hmm I figured out that the problem only occurs when using RealTime PipelineType. I have a DiameterPeer that extends AbstractRTAdapter and it seems there lies my problem. Using only transactional pipes dosen't produce this problem. I have to look into that more closely.

**Comment by skymania** [comment]
Looking at the code now, I think that would be a problem for every AbstractRTAdapter implementation. The thread keeps running indefinitely, and because its is present in ThreadGroup, even after shutdown command  the activeCount dosen't get reduced to 0.

**Comment by isparkes** [comment]
Yes, I see. I'll make a test case for it, then apply your pull, and let's see if that fixes it. Thanks for the contribution!

**Comment by skymania** [comment]
Ok, great.

**Comment by isparkes** [comment]
Many thanks for that. I have added a test for the issue, and applied your pull to resolve it.

We should be good again now!
